### ISSUE TITLE
Don't know how to run under the vscode debugger

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/vr2gather-orchestrator-v2#12]
Trying to debug the orchestrator with vscode (after building with `yarn`) doesn't work, it seems it can't with run with the normal `node bin/build.js`.

Googling for "vscode debug yarn" seems to suggest this is difficult? Please add some information to the readme...

**Comment by troeggla** [comment]
I added a launch configuration for `node` under `./vscode/launch.json`, which compiles the project using `webpack` and then launches the orchestrator in debug mode.

**Comment by troeggla** [comment]
The launch configuration is called *Build & Launch Server*
