### ISSUE TITLE
Need warning about building the container, I think....

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/vr2gather-orchestrator-v2#22]
I get the impression that the `config` directory is now included in the orchestrator docker image (as opposed to the orchestrator v1, which mounted it from the host).

But that means that if you change anything you must re-run `docker compose build`. And the README didn't point this out, it states that `docker compose up` will build the container if needed.

I'm also not 100% sure whether any containers I build are uploaded to our registry, the name seems to suggest so, but I'm not sure.

**Comment by troeggla** [comment]
Yes it is. I agree, I should probably change that.

Yeah, the name indicates that it will be uploaded to our registry if you do `docker push`, but I think I haven't done so in a while. Maybe it's worth setting up a Github action which builds the image and pushes it to our registry whenever a new tag is created.

**Comment by jackjansen** [comment]
Hmm. And it seems that the `.env` file is also used at `docker compose build` time.

**Comment by troeggla** [comment]
You can override `.env` values using environment variables (or the `environment` section of `docker-compose.yml`. But yeah, `.env` should probably be added to `.dockerignore`
