### ISSUE TITLE
Maybe EXTERNAL_HOSTNAME should be overridable dynamically

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/vr2gather-orchestrator-v2#23]
If it is possible to determine the hostname that was used for the current orchestrator connection (which I think should be the case: it's somewhere in the HTTP headers of the original request) it might be a good idea to use that in stead of `EXTERNAL_HOSTNAME` when building URLs for SFUs, etc.

It would solve two issues. First, when connecting to a multi-homed orchestrator (such as our `vrtnuc`) the client will use the same network interface when connecting to an SFU. Second, and more important practically, Windows has continuous issues with resolving MDNS addresses. Sometimes it works fine, sometimes it doesn't work, sometimes it sometimes works.

There's a workaround for VR2Gather (during developing at home): I can simply put the orchestrator IP address in the config file in stead of the `.local` address. But if the orchestrator then replies with SFU addresses that have the `.local` again things still don't work.

**Comment by troeggla** [comment]
If `EXTERNAL_HOSTNAME` in `.env` is left unset or set to `dynamic`, the server will try to determine the external hostname from the request header when creating a new session. An error will be raised if it fails to do so.
