### ISSUE TITLE
External packages in wrong (sub)directory

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/vr2gather-orchestrator-v2#28]
Currently, the WebRTC peer and SFU are stored in `config/packages/webrtc/webrtc/bin` instead of the expected `config/packages/webrtc/bin` that is indicated in `webrtc-config.json`. This problem can be solved e.g. by changing the second-to-last line in `get_webrtc_sfu.sh` from `mv tmp/webrtc ../config/packages/webrtc` to `mv tmp/webrtc/* ../config/packages/webrtc`, although many alternatives exist.

**Comment by jackjansen** [comment]
I _think_ that it is actually #31 that is behind your issue. Let's see what @troeggla thinks.
