### ISSUE TITLE
Docker image is not rebuilt after changing /config or /config/packages

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/vr2gather-orchestrator-v2#31]
If you just follow the instructions and do `docker compose up` it doesn't rebuild.

And actually doing a manual `docker compose build` also doesn't do anything.

The workaround is to first delete all docker images. Then it rebuilds correctly.

**Comment by troeggla** [comment]
I added instructions to the README. It should be sufficient to stop the container, rebuild it and launch it again.
