### ISSUE TITLE
Wrong path to TCP reflector code

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/vr2gather-orchestrator-v2#34]
In the sample config file for TCP reflector, the following is mentioned:

```
"commandLine": [
    "python3",
    "/code/tcpreflector/tcpreflector.py",
    "--host",
    "0.0.0.0",
    "--port",
    "%SFU_PORT%"
  ]
```

This results in:

```
SystemException: TransportProtocolTCPSFU: tcp://193.190.127.250:8089: No connection could be made because the target machine actively refused it.
```

This is because the code for TCP reflector is in `tcpreflector/tcpreflector.py`. Modifying this line results in a valid session.

**Comment by troeggla** [comment]
I'm not quite sure I understand the problem. The SFU launches for me just fine with the given config.

**Comment by jvdrhoof** [comment]
The directory `code` does not exist. The config file however mentions `/code/tcpreflector/tcpreflector.py`. For us, TCP reflector only works after changing this configuration setting to `/tcpreflector/tcpreflector.py`.

**Comment by troeggla** [comment]
Ah I see. That path is set up for running inside a container, which mounts the directory tree under `/code` inside the container.

**Comment by troeggla** [comment]
I made the change you requested, since the relative path also works inside the container.
